### ISSUE TITLE
Устранение коллизии между models.businesslogic.Question и models.entities.Question

### ISSUE THREAD

**Issue by procudin** [procudin/CompPrehension#26]
Предлагаю переименовать либо все Entity-objects, добавив к ним определенный постфикс/префикс, либо переименовать models.businesslogic.Question в какой-нибудь models.businesslogic.QuestionAggregate или еще как-нибудь. А то эти коллизии уже раздражают. Отпишитесь в комментах, как вам кажется лучше. Я бы конечно за второй вариант, тк он попроще :D

**Comment by ShadowGorn** [comment]
Я скорее за первый, но в целом мне не так принципиально

**Comment by procudin** [comment]
Ну тогда добавлю постфикс "...Entity" к всем объектам бд

**Comment by oasychev** [comment]
Мы насколько я помню уже говорили об этом переименовании еще в самом начале, но, к сожалению, не записали тут решений.

**Comment by oasychev** [comment]
Но Aggregate как суффикс мне не нравится. Префиксы или суффиксы должны быть систематичными.
