### ISSUE TITLE
Ошибки в mysql

### ISSUE THREAD

**Issue by procudin** [procudin/CompPrehension#27]
Как оказалось, та бд, которая используется для unit-тестов, не делает проверки constrait'ов бд. Например, у меня вылетает здесь на моменте сохранения:

![image](https://user-images.githubusercontent.com/20419403/103483909-a37de900-4dfb-11eb-9419-9a513d101e76.png)

Вылетает, тк для Response не задан объект интеракции, у для которого есть констрейт:
![image](https://user-images.githubusercontent.com/20419403/103484011-77169c80-4dfc-11eb-851d-ffa59a3a6f8f.png)

Для юнит-тестов все норм работает. Возникает вопрос о консистентности тестовой среды и рабочей...

**Comment by oasychev** [comment]
Это вопрос в первую очередь к Ярославу, но он временно недоступен.

**Comment by procudin** [comment]
крч пофиксил, ошибка как оказалось связана с моей тестовой средой, помог дроп базы
